# Generated by Django 4.2.6 on 2024-07-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
